services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092' # <--- Flask usará esto
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka:/var/lib/kafka/data

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    profiles: ["db_mongo"]  # <--- Solo sube si pides mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    profiles: ["db_cassandra"] # <--- Solo sube si pides cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  spark:
    build:
      context: .
      dockerfile: docker/dockerfile.spark
    container_name: spark
    ports:
      - "8080:8080" # Web UI del Master
      - "7077:7077" # Puerto de comunicación
    volumes:
      - .:/app
    working_dir: /app

  spark-worker:
    build:
      context: .
      dockerfile: docker/dockerfile.spark
    container_name: spark-worker
    depends_on:
      - spark
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SPARK_MASTER=spark://spark:7077
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077

  flask:
    build:
      context: .
      dockerfile: docker/dockerfile.python
    container_name: flask
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - PROJECT_HOME=/app/  