FROM python:3.9-slim

RUN pip install flask flask-socketio kafka-python boto3 cassandra-driver iso8601 python-dotenv requests

COPY web/ /app/web/
COPY scripts/ /app/scripts/
COPY requirements.txt /app/
WORKDIR /app

CMD ["python3", "web/app.py"]
