FROM apache/airflow:latest-python3.12

USER root
RUN apt-get update && apt-get install -y curl python3-pip && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir mlflow boto3 apache-airflow-providers-http
