spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lakehouse org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type hadoop
spark.sql.catalog.lakehouse.warehouse s3a://lakehouse/warehouse/

spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem

# Derby config: database location and log file
spark.hadoop.javax.jdo.option.ConnectionURL jdbc:derby:data/metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName org.apache.derby.jdbc.EmbeddedDriver
spark.driver.extraJavaOptions -Dderby.stream.error.file=logs/derby.log
spark.executor.extraJavaOptions -Dderby.stream.error.file=logs/derby.log
