apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  namespace: ibdn
spec:
  serviceName: spark-worker
  replicas: 3
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      dnsConfig:
        searches:
          - spark-worker.ibdn.svc.cluster.local
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - spark-worker
              topologyKey: kubernetes.io/hostname
      containers:
      - name: spark-worker
        image: europe-west1-docker.pkg.dev/REPLACE_PROJECT/ibdn/spark:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MASTER
          valueFrom:
            configMapKeyRef:
              name: ibdn-config
              key: SPARK_MASTER_URL
        - name: SPARK_WORKER_MEMORY
          value: "6G"
        - name: SPARK_WORKER_CORES
          value: "4"
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
        command:
        - /bin/sh
        - -c
        - /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: ibdn
spec:
  clusterIP: None
  selector:
    app: spark-worker
  ports:
  - port: 8081